name: web
app_id: da_Ko6IotJUbZQZ
owner: offlead
package: .
kind: wasmer.io/App.v0
annotations:
  shipitcli.com/config:
    commands: {}
    cross_platform: wasix_wasm32
    extra_dependencies:
    - uvicorn
    framework: flask
    install_requires_all_files: false
    main_file: src/main.py
    port: 8080
    precompile_python: true
    python_extra_index_url: https://pythonindex.wasix.org/simple
    python_version: '3.13'
    server: uvicorn
    uses_ffmpeg: false
    uses_pandoc: false
    uv_version: 0.8.15
    wsgi_application: src.main:app
  shipitcli.com/provider: python
  shipitcli.com/version: 0.21.5
